config/routes.rb
Rails.application.routes.draw do

  mount Rich::Engine => '/rich', :as => 'rich'
  mount Ckeditor::Engine => '/ckeditor'
  ActiveAdmin.routes(self)
  root 'static_pages#index'

  #get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get :about, to: 'static_pages#about'
  get :contacts, to: 'static_pages#contacts'

  #resources :users
  resources :sessions
  resources :items
  resources :requests
  resources :email_subscriptions, only: :create
  resources :articles

  %w(404 422 500 503).each do |code|
    get code, to: "errors#show", code: code
  end
end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id          :integer          not null, primary key
#  title       :string
#  description :string
#  price       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  kind        :string
#  images      :string           is an Array
#  featured    :boolean
#

class Item < ActiveRecord::Base
  mount_uploaders :images, ImageUploader

  scope :of_kind, -> kind { where(kind: kind) }
  scope :without, -> id { where.not(id: id)}
  scope :by_created, -> { order(created_at: :desc) }
  scope :featured, -> { where(featured: true) }
  scope :by_category_position, -> { joins(:category).order('categories.position asc') }

  validates :discount, inclusion: { in: 0..99 }

  belongs_to :category

  before_save :update_category, if: -> { changed_attributes['kind'].present? }

  def price_with_discount
    (100 - discount) / 100.to_f * price.to_i
  end

  def update_category
    self.category = Category.find_by(name: kind)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # before_filter :authorize, except: [:show, :index]

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(valid_params)
    @item.images = images_param
    if @item.save
      redirect_to @item
    else
      render 'new'
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.attributes = valid_params
    @item.images = images_param
    @item.save
    redirect_to @item
  end

  def index
    @optom = params[:of_kind] == 'Оптом'

    @items = if(kind = params[:of_kind])
      Item.of_kind kind
    else
      Item.all
    end.by_category_position.by_created

    render layout: 'full_width'
  end

  def show
    @item = Item.find(params[:id])
    @related_items = Item.of_kind(@item.kind).without(@item.id).last(3)
    @request = Request.new
  end

  def upload_image
    image = Upload.new image: params[:file]
    image.save
    render json: image.image.url
  end

  def destroy
    Item.delete(params[:id])
    redirect_to :back
  end

  private

  def valid_params
    params.
      require(:item).
      permit(:description, :title, :images, :price, :kind, :sizes, :featured, :discount)
  end

  def images_param
    params['item']['images']
  end
end

app/helpers/items_helper.rb
module ItemsHelper
  def leather_options
    Category.pluck(:name).map { |c| [c, c] }
  end
end

app/views/items/edit.haml
.clearfix
  .col-sm-3
  .col-sm-6
    = form_for @item do |f|
      .form-group
        = f.text_field :title, class: 'form-control', placeholder: 'Название'
      .form-group
        .input-group
          = f.text_field :price, class: 'form-control', placeholder: 'Цена'
          .input-group-addon ₽
      .form-group
        = f.text_area :description, class: 'form-control', placeholder: 'Описание'
      .form-group
        = f.label :title, 'Размеры'
        = f.text_field :sizes, class: 'form-control', placeholder: '36, 37, 38, 39'
      .form-group
        = f.label :title, 'Зафичирить'
        = f.check_box :featured
      .form-group
        = f.label :title, 'Тип'
        = f.select :kind, leather_options, class: 'form-control'
      .form-group
        = f.label :discount, 'Скидка', type: :number
        = f.text_field :discount, class: 'form-control', pattern: '\d*', maxlength: '2'
      .form-group
        = f.file_field :images, multiple: true
      = f.submit "Post"
  .col-sm-3

app/views/items/index.html.haml
- page_title(item_title)
.menu
  .container
    %ul.justify-content-center.row.text-uppercase.lato.center-block.text-center
      %li
        = link_to 'Все', items_path, class: ('active' if params[:of_kind].blank?)
      - leather_options.each do |kind, _|
        %li
          = link_to kind, items_path(of_kind: kind), class: ('active' if params[:of_kind] == kind)
.container
  .all-items.clearfix
    .row
      - @items.each_slice(3) do |groups|
        = render collection: groups, partial: '/shared/items/grid_item', as: :item

app/views/items/new.html.haml
.clearfix
  .col-sm-3
  .col-sm-6
    = form_for @item do |f|
      .form-group
        = f.text_field :title, class: 'form-control', placeholder: 'Название'
      .form-group
        .input-group
          = f.text_field :price, class: 'form-control', placeholder: 'Цена'
          .input-group-addon ₽
      .form-group
        = f.text_area :description, class: 'form-control', placeholder: 'Описание'
      .form-group
        = f.label :title, 'Зафичирить'
        = f.check_box :featured
      .form-group
        = f.label :title, 'Тип'
        = f.select :kind, leather_options, class: 'form-control'
      .form-group
        = f.file_field :images, multiple: true
      = f.submit "Post"
  .col-sm-3

app/views/items/show.html.haml
- page_title(@item.title)

.product.container
  .row
    .col-md-6.col-12
      .img-responsive.background-image
        = image_tag @item.images.first.medium.url, class: 'img-fluid', id: 'main-production-image'
        - if @item.images.count > 1
          .row.select-image-block
            - @item.images.each do |image|
              .col-2
                .product-image-block{:style => "background-image: url(#{image.small.url})"}

    .col-md-6.col-12
      .product-type-tag= @item.kind
      %h1.product-title= @item.title
      - if @item.price.present? && @item.price.to_i > 0
        - if @item.discount.zero?
          .price-tag.big= number_to_currency @item.price, delimiter: ' ', unit: "₽", format: "%n %u", precision: 0
        - else
          .price-tag.big
            = number_to_currency @item.price_with_discount, delimiter: ' ', unit: "₽", format: "%n %u", precision: 0
            .line-through.d-inline.grey= number_to_currency @item.price, delimiter: ' ', unit: "₽", format: "%n %u", precision: 0

      - if @item.sizes.present?
        .sizes
          %p Размеры:
          - @item.sizes.split(', ').each do |size|
            .size= size
      .clearfix
        .hollow-button.product#leave-request.bold Оставить заявку
        = form_for @request, remote: true, html: { id: 'request-form', class: 'row' }, url: requests_url do |f|
          = f.text_field :contact, placeholder: 'Ваш телефон или почта', class: 'request lato text-uppercase col-sm-8'
          = f.hidden_field :request, value: "Запрос был сделан со страницы: #{item_url(@item)}"
          = f.submit 'Отправить', class: 'hollow-button col-sm-4 bold'
      %p= @item.description

.you-might-like.mirta-header.text-center
  %h1 Вам может понравиться
  .row
    = render collection: @related_items, partial: '/shared/items/grid_item', as: :item