config/routes.rb
Rails.application.routes.draw do

  mount Rich::Engine => '/rich', :as => 'rich'
  mount Ckeditor::Engine => '/ckeditor'
  ActiveAdmin.routes(self)
  root 'static_pages#index'

  #get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get :about, to: 'static_pages#about'
  get :contacts, to: 'static_pages#contacts'

  #resources :users
  resources :sessions
  resources :items
  resources :requests
  resources :email_subscriptions, only: :create
  resources :articles

  %w(404 422 500 503).each do |code|
    get code, to: "errors#show", code: code
  end
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id          :integer          not null, primary key
#  title       :string
#  text        :text
#  views       :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  image       :string
#  description :text
#  images      :string           is an Array
#

class Article < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  mount_uploaders :images, ImageUploader
end

app/models/category.rb
class Category < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  acts_as_list

  scope :ordered, -> { order(position: :asc)}

  default_scope { ordered }
end

app/models/email_subscription.rb
# == Schema Information
#
# Table name: email_subscriptions
#
#  id    :integer          not null, primary key
#  email :string
#

class EmailSubscription < ActiveRecord::Base
  EMAIL_VALIDATION_REGEXP = /\A\w([\w+.=\-]*\w)?@\w([\w\-]*\.)+\w+\z/

  validates :email, format: { with: EMAIL_VALIDATION_REGEXP }
end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id          :integer          not null, primary key
#  title       :string
#  description :string
#  price       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  kind        :string
#  images      :string           is an Array
#  featured    :boolean
#

class Item < ActiveRecord::Base
  mount_uploaders :images, ImageUploader

  scope :of_kind, -> kind { where(kind: kind) }
  scope :without, -> id { where.not(id: id)}
  scope :by_created, -> { order(created_at: :desc) }
  scope :featured, -> { where(featured: true) }
  scope :by_category_position, -> { joins(:category).order('categories.position asc') }

  validates :discount, inclusion: { in: 0..99 }

  belongs_to :category

  before_save :update_category, if: -> { changed_attributes['kind'].present? }

  def price_with_discount
    (100 - discount) / 100.to_f * price.to_i
  end

  def update_category
    self.category = Category.find_by(name: kind)
  end
end

app/models/request.rb
# == Schema Information
#
# Table name: requests
#
#  id         :integer          not null, primary key
#  request    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  contact    :string
#

class Request < ActiveRecord::Base
  validates :contact, presence: true
end

app/models/seo_content.rb
class SeoContent < ActiveRecord::Base
  validates :title, :meta_description, :address, :content, :meta_keywords, presence: true
end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string
#  password_digest :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  has_secure_password
  validates :email, uniqueness: true, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :authorize, except: [:show, :index]

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(valid_params)
    @article.images = images_param
    @article.save
    redirect_to articles_path
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.images = images_param
    @article.update!(valid_params)
    redirect_to @article
  end

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
    render layout: 'full_width'
  end

  def destroy
    @article = Article.delete(params[:id])
    redirect_to :back
  end

  private

  def images_param
    params['article']['images']
  end

  def valid_params
    params.require(:article).permit(:text, :title, :image, :description, :meta_description)
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def show(code: 404)
    if code == 404
      render 'errors/show', status: 404
    else
      render file: "public/#{code}.html", status: code
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # before_filter :authorize, except: [:show, :index]

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(valid_params)
    @item.images = images_param
    if @item.save
      redirect_to @item
    else
      render 'new'
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.attributes = valid_params
    @item.images = images_param
    @item.save
    redirect_to @item
  end

  def index
    @optom = params[:of_kind] == 'Оптом'

    @items = if(kind = params[:of_kind])
      Item.of_kind kind
    else
      Item.all
    end.by_category_position.by_created

    render layout: 'full_width'
  end

  def show
    @item = Item.find(params[:id])
    @related_items = Item.of_kind(@item.kind).without(@item.id).last(3)
    @request = Request.new
  end

  def upload_image
    image = Upload.new image: params[:file]
    image.save
    render json: image.image.url
  end

  def destroy
    Item.delete(params[:id])
    redirect_to :back
  end

  private

  def valid_params
    params.
      require(:item).
      permit(:description, :title, :images, :price, :kind, :sizes, :featured, :discount)
  end

  def images_param
    params['item']['images']
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_filter :authorize, except: [:new, :create]

  def new
    @request = Request.new
  end

  def index
    @requests = Request.all
  end

  def create
    @request = Request.new(valid_params)
    if @request.save
      NotifyTelegram.new(@request).call
      head :created
    else
      head :bad_request
    end
  end

  def valid_params
    params.require(:request).permit(:contact, :request)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(valid_params)
    if @user.save
      sesstion[:user_id] = @user.id
      redirect_to root_path, notice: "Спасибо за регистрацию"
    else
      render "new", notice: "Произошла ошибка, скорее всего вы уже зарегестрированны"
    end
  end

  private

  def valid_params
    params.require(:user).permit(:password, :email, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  DEFAULT_META_DESCRIPTION = "Приветствуем вас в интернет-магазине дизайнерской обуви, рюкзаков, сумок и " \
    "других аксессуаров из натуральной кожи. Устали от банальных вещей? Здесь вы " \
    "однозначно найдете шикарные эксклюзивные изделия, соответствующие вашим " \
    "представлениям о стиле и красоте!".freeze

  def page_title(title= nil, add_extra: false)
    return seo_content.title if seo_content.present?
    @title ||= title || ''

    if add_extra
      "#{@title} Дизайнерская обувь и аксессуары из натуральной кожи в магазине 13РМ"
    else
      @title
    end
  end

  def meta_keywords
    return seo_content.meta_keywords if seo_content.present?
    "Дизайнерская обувь, сумки из натуральной кожи, кожанные рюкзаки"
  end

  def meta_description(description = nil)
    return seo_content.meta_description if seo_content.present?
    @meta_description ||= description || DEFAULT_META_DESCRIPTION
  end

  def item_title
    case params[:of_kind].to_s
    when '' then "Каталог кожи"
    when 'Оптом' then "Кожа оптом"
    else "Кожа для #{params[:of_kind].downcase}"
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  def leather_options
    Category.pluck(:name).map { |c| [c, c] }
  end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.haml
%footer
  .block
    %ul.social-networks
      %li= link_to "Facebook", "https://www.facebook.com/13PM-257590778167036/"
      %li ■
      %li= link_to "Instagram", "https://www.instagram.com/13p.m._/"
      %li ■
      %li= link_to "VKontakte", "https://vk.com/13pm.store"
:javascript
  (function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter50181952 = new Ya.Metrika2({ id:50181952, clickmap:true, trackLinks:true, accurateTrackBounce:true, webvisor:true }); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = "https://mc.yandex.ru/metrika/tag.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks2");
%noscript
  %div
    %img{:alt => "", :src => "https://mc.yandex.ru/watch/50181952", :style => "position:absolute; left:-9999px;"}/

app/views/layouts/_general_layout.html.haml
%body
  - if flash[:notice].present?
    .notice= flash[:notice]
  %header.site__header
    .container
      %ul.row
        .logo.text-center.col-12.d-block.d-sm-none.nav__link-element
          = link_to root_path, class: 'logo mirta text-uppercase' do
            = image_tag asset_path('logo.png'), class: 'image__logo'
        %li.col-12.col-sm-2.nav__link-element= link_to 'Каталог', items_path
        %li.col-12.col-sm-2.nav__link-element= link_to 'Статьи', articles_path
        .logo.text-center.col-sm-4.d-none.d-sm-block.nav__link-element
          = link_to root_path, class: 'logo mirta text-uppercase' do
            = image_tag asset_path('logo.png'), class: 'image__logo'
        %li.col-12.col-sm-2.nav__link-element= link_to 'Контакты', contacts_path
        %li.col-12.col-sm-2.nav__link-element= link_to 'О нас', about_path
  - if full_width
    = yield
  - else
    %main
      = yield
  - if seo_content.present?
    .container
      .row
        .seo-content.col-md-8.col-xs-10
          = seo_content.content.html_safe

app/views/layouts/_head.html.haml
%title= page_title
%meta{ name: 'keywords', content: meta_keywords }
%meta{ name: 'description', content: meta_description }
%meta{ name: 'viewport', content: 'width=device-width, initial-scale=1, shrink-to-fit=no' }

= stylesheet_link_tag    'application', media: 'all', async: true, cache: true
= javascript_include_tag 'application'
= csrf_meta_tags

app/views/layouts/application.html.haml
!!!
%html
  = render partial: '/layouts/head'

  = render partial: '/layouts/general_layout', locals: { full_width: false }

  = render partial: '/layouts/footer'

app/views/layouts/full_width.html.haml
!!!
%html
  = render partial: '/layouts/head'

  = render partial: '/layouts/general_layout', locals: { full_width: true }

  = render partial: '/layouts/footer'